name: Email-step CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 22f1001438@ds.study.iitm.ac.in
        run: |
          echo "Hello, world!"
          echo "This step name contains the requested email address."
